---
title: "Portfolio 1"
author: Emilie Munch Andreasen, Gergana Atanasova, Jakob Thygesen, Márton Kardos,
  Natasha Kouznetsova Jørgensen
date: "7/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
_Type:_ Group assignment
_Due:_ 13 March 2022, 23:59
---

Please submit your answers on GitHub Classroom. The best way to give your answers is in a LaTeX or R Markdown file, but you can also create a PDF in some other way.

---

1) Given the vectors $\vec{u} = (1,1,1)$, $\vec{v} = (2,3,1)$, and
$\vec{w} = (-1,-1,2)$, compute the following products:
    a) $\vec{u} \cdot \vec{v}$
$$
[1,1,1]\cdot[2,3,1]=2+3+1=6
$$
    b) $\vec{u} \cdot \vec{w}$
$$
[1,1,1]\cdot[-1,-1,2]=-1+(-1)+2=0
$$
    c) $\vec{v} \cdot \vec{w}$
$$
[2,3,1]\cdot[-1,-1,2]=-2+(-3)+2=-3
$$
    d) $\vec{u} \times \vec{v}$
$$ 
[1,1,1]\times[2,3,1]=\begin{bmatrix}
1 & 1 & 1 \\
2 & 3 & 1 \\
\end{bmatrix}
=[1*1-1*3,1*2-1*1,1*3-1*2]=[-2,1,1]
$$
    e) $\vec{u} \times \vec{w}$
$$
[1,1,1]\times[-1,-1,2]=\begin{bmatrix}
1 & 1 & 1 \\
-1 & -1 & 2 \\
\end{bmatrix}
=
[1*2-1*(-1), 1*(-1)-1*2, 1*(-1)-1*(-1)]=[3,-3,0]
$$
    f) $\vec{v} \times \vec{w}$
$$
[2,3,1]\times[-1,-1,2]=
\begin{bmatrix}
2 & 3 & 1 \\
-1 & -1 & 2 \\
\end{bmatrix}
=
[3*2-1*(-1), 1*(-1)-2*2,2*(-1)-3*(-1)]=[7,-5,1]
$$
---

2) Vectors are _orthogonal_ (or _perpendicular_) when their dot product is zero: $\vec{x} \perp \vec{y} \Longleftrightarrow \vec{x} \cdot \vec{y} = 0$. A _unit vector_ is a vector with norm 1: $\Vert \vec{x} \Vert = 1$.
    a) Find a unit vector that is perpendicular to both $\vec{u} = (1,0,1)$ and $\vec{v} = (1,2,0)$.
    b) Find a vector that is orthogonal both to $\vec{u}_1 = (1,0,1)$ and $\vec{u}_2 = (1,3,0)$, and whose dot product with the vector $\vec{v} = (1,1,0)$ is equal to 8.
    
---

3) Prove the geometric formula for the dot product $\vec{x} \cdot \vec{y} = \Vert \vec{x} \Vert \Vert \vec{y} \Vert \cos \varphi$, where $\varphi$ is the angle between the vectors $\vec{x}$ and $\vec{y}$.

---

4) For the matrix
$$
X = \begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 & 1
\end{bmatrix},
$$
calculate $X^n$ for $n = 2, 3,4, 5$. Write a rule for calculating higher values of $n$.

$$
X = \begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 & 1
\end{bmatrix}
$$

$$
X² = \begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 & 1
\end{bmatrix} \cdot \begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 & 1
\end{bmatrix} = \begin{bmatrix}
1 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 & 2
\end{bmatrix}
$$

$$
X³ = \begin{bmatrix}
1 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 & 2
\end{bmatrix} \cdot \begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 & 1
\end{bmatrix} = \begin{bmatrix}
1 & 0 & 2 \\
0 & 1 & 0 \\
2 & 0 & 3
\end{bmatrix}
$$


$$
X⁴ = \begin{bmatrix}
1 & 0 & 2 \\
0 & 1 & 0 \\
2 & 0 & 3
\end{bmatrix} \cdot \begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 & 1
\end{bmatrix} = \begin{bmatrix}
2 & 0 & 3 \\
0 & 1 & 0 \\
3 & 0 & 5
\end{bmatrix}
$$

$$
X⁵ = \begin{bmatrix}
2 & 0 & 3 \\
0 & 1 & 0 \\
3 & 0 & 5
\end{bmatrix} \cdot \begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 & 1
\end{bmatrix} = \begin{bmatrix}
3 & 0 & 5 \\
0 & 1 & 0 \\
5 & 0 & 8
\end{bmatrix}
$$

$$
f: \mathbb{N} \Longrightarrow \mathbb{N} \\
f(0) = 0 \\
f(1) = 1 \\
f(n) = f(n-1) + f(n-2) \\
X^n = \begin{bmatrix}
f(n) & 0 & f(n+1) \\
0 & 1 & 0 \\
f(n+1) & 0 & f(n+2)
\end{bmatrix}
$$
